"""Generate 1000+ trading Q&A pairs for trading_knowledge.txt."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "raw" / "trading_knowledge.txt"

KNOWLEDGE = {
    "a limit order": "A limit order is an instruction to buy or sell at a specific price or better, giving price control but no guarantee of execution.",
    "a market order": "A market order executes immediately at the best available price, prioritizing speed over exact price.",
    "a stop-loss order": "A stop-loss order closes a position when price reaches a preset level to cap losses.",
    "a take-profit order": "A take-profit order automatically closes a trade at a target price to lock in gains.",
    "a stop-limit order": "A stop-limit order triggers a limit order once a stop price is hit, combining stop protection with price control.",
    "a trailing stop": "A trailing stop moves with favorable price action and exits if price reverses by a set amount.",
    "a bracket order": "A bracket order places entry, stop-loss, and take-profit levels together as one trade plan.",
    "a good-till-cancelled order": "A GTC order stays active until filled or manually cancelled, unlike day orders.",
    "a fill-or-kill order": "An FOK order must execute completely immediately or be cancelled.",
    "a day order": "A day order expires at the end of the trading session if not filled.",
    "bid price": "The bid is the highest price buyers are willing to pay for an asset at a given moment.",
    "ask price": "The ask is the lowest price sellers are willing to accept for an asset.",
    "bid-ask spread": "The spread is the gap between bid and ask; tighter spreads usually mean better liquidity.",
    "liquidity": "Liquidity is how easily an asset can be bought or sold without moving price much.",
    "volume": "Volume measures how many shares or contracts traded in a period and confirms price moves.",
    "open interest": "Open interest counts outstanding derivative contracts not yet closed or expired.",
    "market depth": "Market depth shows resting buy and sell orders at multiple price levels.",
    "slippage": "Slippage is the difference between expected and actual execution price, common in fast markets.",
    "volatility": "Volatility measures how much price fluctuates; higher volatility means larger swings.",
    "implied volatility": "Implied volatility reflects the market's expectation of future price movement, especially in options.",
    "historical volatility": "Historical volatility measures past price swings over a lookback period.",
    "beta": "Beta compares a stock's movement to the broader market; beta above 1 means more volatile than the index.",
    "alpha": "Alpha measures performance above a benchmark after adjusting for risk.",
    "sharpe ratio": "The Sharpe ratio compares return to risk; higher values suggest better risk-adjusted performance.",
    "drawdown": "Drawdown is the peak-to-trough decline in account or asset value during a losing period.",
    "risk-reward ratio": "Risk-reward compares potential loss to potential gain, helping traders evaluate setups.",
    "position sizing": "Position sizing decides how much capital to risk per trade based on account size and stop distance.",
    "risk per trade": "Risk per trade is the fixed percentage or dollar amount you are willing to lose on one idea.",
    "leverage": "Leverage lets traders control a larger position with less capital, magnifying gains and losses.",
    "margin": "Margin is borrowed capital from a broker used to open larger positions than cash alone allows.",
    "margin call": "A margin call happens when account equity falls below required levels and the broker demands more funds.",
    "maintenance margin": "Maintenance margin is the minimum equity required to keep leveraged positions open.",
    "initial margin": "Initial margin is the deposit needed to open a leveraged position.",
    "long position": "Going long means buying an asset expecting its price to rise.",
    "short position": "Going short means selling borrowed assets expecting price to fall so you can buy back cheaper.",
    "short selling": "Short selling profits from declining prices but carries unlimited loss potential if price rises.",
    "covering a short": "Covering means buying back shares to close a short position.",
    "hedging": "Hedging reduces exposure to adverse price moves using offsetting positions or instruments.",
    "diversification": "Diversification spreads risk across assets, sectors, or strategies so one loss does not dominate.",
    "correlation": "Correlation shows how two assets move together; low correlation helps portfolio stability.",
    "portfolio": "A portfolio is the collection of all positions and cash a trader or investor holds.",
    "asset allocation": "Asset allocation divides capital among stocks, bonds, commodities, and cash by strategy and risk.",
    "rebalancing": "Rebalancing adjusts portfolio weights back to target allocations after market moves.",
    "compound interest": "Compound interest grows capital as gains earn additional returns over time.",
    "equity curve": "An equity curve plots account value over time to visualize performance and drawdowns.",
    "backtesting": "Backtesting evaluates a strategy on historical data before risking live capital.",
    "forward testing": "Forward testing runs a strategy on new live or paper data to confirm real-world behavior.",
    "paper trading": "Paper trading simulates orders without real money to practice execution and discipline.",
    "live trading": "Live trading uses real capital and real market fills, adding emotional and financial consequences.",
    "demo account": "A demo account provides simulated trading conditions for learning platform mechanics.",
    "broker": "A broker is the intermediary that routes orders to exchanges and holds your account.",
    "exchange": "An exchange is a regulated marketplace where buyers and sellers meet to trade securities or derivatives.",
    "ECN": "An electronic communication network matches buy and sell orders directly between participants.",
    "market maker": "A market maker quotes bid and ask prices to provide liquidity and earn the spread.",
    "clearing house": "A clearing house guarantees trade settlement and manages counterparty risk.",
    "settlement": "Settlement is when ownership and payment officially transfer after a trade.",
    "T+1 settlement": "T+1 means trades settle one business day after execution.",
    "tick size": "Tick size is the minimum price increment an asset can move.",
    "lot size": "Lot size is the standard quantity traded, such as 100 shares or a forex micro lot.",
    "pip": "A pip is a standard unit of price change in forex, usually 0.0001 for most pairs.",
    "pipette": "A pipette is one-tenth of a pip, offering finer price quoting on some platforms.",
    "contract size": "Contract size defines how much underlying asset one futures or CFD contract represents.",
    "notional value": "Notional value is total exposure calculated as price times quantity or contract multiplier.",
    "capitalization": "Market capitalization equals share price times shares outstanding and ranks company size.",
    "float": "The float is shares available for public trading, excluding closely held stock.",
    "outstanding shares": "Outstanding shares are all shares issued by a company currently held by investors.",
    "earnings per share": "EPS is net income divided by shares outstanding and shows profit per share.",
    "price-to-earnings ratio": "The P/E ratio compares share price to earnings and helps value a company.",
    "price-to-book ratio": "P/B compares market price to book value of equity on the balance sheet.",
    "dividend yield": "Dividend yield is annual dividend divided by share price, showing income return.",
    "ex-dividend date": "On the ex-dividend date, buyers no longer receive the upcoming dividend payment.",
    "earnings report": "An earnings report releases quarterly financial results and often moves stock prices.",
    "guidance": "Company guidance is management's forecast of future revenue, earnings, or growth.",
    "revenue": "Revenue is total sales before expenses; growth trends matter for valuation.",
    "net income": "Net income is profit after all expenses, taxes, and interest.",
    "cash flow": "Cash flow tracks actual cash entering and leaving a business, beyond accounting profit.",
    "balance sheet": "A balance sheet lists assets, liabilities, and equity at a point in time.",
    "income statement": "An income statement shows revenue, expenses, and profit over a period.",
    "fundamental analysis": "Fundamental analysis evaluates economic value using financials, industry, and macro factors.",
    "technical analysis": "Technical analysis studies price, volume, and indicators to forecast future moves.",
    "support level": "Support is a price zone where buying interest tends to stop or reverse a decline.",
    "resistance level": "Resistance is a price zone where selling pressure tends to cap or reverse a rally.",
    "breakout": "A breakout occurs when price moves decisively above resistance or below support on volume.",
    "breakdown": "A breakdown is a bearish move through support, often signaling further downside.",
    "trend": "A trend is the general direction of price: up, down, or sideways over time.",
    "uptrend": "An uptrend forms higher highs and higher lows, showing sustained buying pressure.",
    "downtrend": "A downtrend forms lower highs and lower lows, showing sustained selling pressure.",
    "sideways market": "A sideways or range-bound market moves between support and resistance without clear trend.",
    "moving average": "A moving average smooths price data to reveal direction; common periods are 20, 50, and 200.",
    "simple moving average": "SMA averages closing prices equally over a chosen number of periods.",
    "exponential moving average": "EMA weights recent prices more heavily, reacting faster to new data.",
    "golden cross": "A golden cross happens when a short-term MA crosses above a long-term MA, often viewed as bullish.",
    "death cross": "A death cross happens when a short-term MA crosses below a long-term MA, often viewed as bearish.",
    "RSI": "The Relative Strength Index measures momentum on a 0-100 scale; above 70 is often overbought, below 30 oversold.",
    "MACD": "MACD tracks the relationship between two EMAs and helps identify momentum shifts and crossovers.",
    "Bollinger Bands": "Bollinger Bands plot volatility channels around a moving average; widening bands signal rising volatility.",
    "stochastic oscillator": "The stochastic compares closing price to recent range to spot overbought and oversold conditions.",
    "ATR": "Average True Range measures volatility and helps set stop distances based on recent price movement.",
    "ADX": "Average Directional Index measures trend strength regardless of direction.",
    "Fibonacci retracement": "Fibonacci levels estimate possible pullback zones using ratios like 38.2%, 50%, and 61.8%.",
    "Fibonacci extension": "Fibonacci extensions project potential profit targets beyond the prior swing.",
    "candlestick chart": "Candlesticks show open, high, low, and close for each period, revealing sentiment quickly.",
    "doji candle": "A doji has nearly equal open and close, signaling indecision at that price level.",
    "hammer candle": "A hammer has a small body and long lower wick, often appearing after declines as potential reversal.",
    "shooting star": "A shooting star has a small body and long upper wick, often appearing after rallies as potential reversal.",
    "engulfing pattern": "An engulfing pattern occurs when one candle's body fully covers the prior candle, suggesting reversal.",
    "head and shoulders pattern": "Head and shoulders is a reversal pattern with three peaks; the middle peak is highest.",
    "inverse head and shoulders": "Inverse head and shoulders is a bullish reversal with three troughs and a breakout above the neckline.",
    "double top": "A double top is a bearish reversal where price fails twice near the same resistance.",
    "double bottom": "A double bottom is a bullish reversal where price holds twice near the same support.",
    "triangle pattern": "Triangles are consolidation patterns where price compresses before a potential breakout.",
    "flag pattern": "A flag is a brief pause in a strong trend before continuation in the same direction.",
    "pennant pattern": "A pennant is a small symmetrical triangle that often continues the prior sharp move.",
    "wedge pattern": "A wedge shows converging trendlines and can signal continuation or reversal depending on context.",
    "cup and handle": "Cup and handle is a bullish continuation pattern resembling a rounded base with a small pullback.",
    "gap": "A gap is an empty space on the chart where price jumps between sessions without trading in between.",
    "gap fill": "Gap fill occurs when price returns to trade through the previously gapped area.",
    "VWAP": "Volume Weighted Average Price is the average price weighted by volume, used as an intraday benchmark.",
    "pivot points": "Pivot points calculate support and resistance from the prior period's high, low, and close.",
    "market profile": "Market profile displays price distribution over time to show where most trading occurred.",
    "order flow": "Order flow analysis tracks live buy and sell activity to gauge immediate supply and demand.",
    "level 2 data": "Level 2 shows the order book depth beyond best bid and ask.",
    "time and sales": "Time and sales lists every executed trade with price, size, and timestamp.",
    "bull market": "A bull market is a prolonged period of rising prices and optimistic sentiment.",
    "bear market": "A bear market is a sustained decline, often defined as 20% or more from recent highs.",
    "correction": "A correction is a short-term pullback, typically 10-20%, within a larger trend.",
    "rally": "A rally is a sharp upward move in price over a relatively short period.",
    "pullback": "A pullback is a temporary move against the prevailing trend before potential continuation.",
    "reversal": "A reversal changes the dominant trend direction after exhaustion or major news.",
    "consolidation": "Consolidation is sideways price action where supply and demand are roughly balanced.",
    "accumulation": "Accumulation is when informed buyers quietly build positions before a potential rise.",
    "distribution": "Distribution is when large holders sell into strength before a potential decline.",
    "market sentiment": "Market sentiment reflects the overall mood of participants, from fear to greed.",
    "fear and greed index": "The fear and greed index combines several indicators to gauge emotional extremes in markets.",
    "put-call ratio": "Put-call ratio compares put to call volume and can signal hedging or speculative bias.",
    "short interest": "Short interest is the percentage of shares sold short and may fuel squeezes if bears cover.",
    "short squeeze": "A short squeeze forces short sellers to buy back shares quickly, accelerating price gains.",
    "gamma squeeze": "A gamma squeeze can amplify moves when options dealers hedge rapidly as prices shift.",
    "insider trading": "Legal insider trading is executives buying or selling their own company stock with required disclosures.",
    "institutional ownership": "Institutional ownership shows how much stock is held by funds and large investors.",
    "retail trader": "A retail trader is an individual participant trading with personal capital, often smaller size.",
    "algorithmic trading": "Algorithmic trading uses automated rules to enter and exit based on predefined logic.",
    "high-frequency trading": "HFT uses ultra-fast systems to exploit tiny price discrepancies for microseconds to milliseconds.",
    "quantitative trading": "Quant trading applies statistical models and data analysis to generate systematic signals.",
    "systematic trading": "Systematic trading follows fixed rules rather than discretionary judgment for each decision.",
    "discretionary trading": "Discretionary trading relies on trader judgment, experience, and contextual interpretation.",
    "day trading": "Day trading opens and closes positions within the same session to avoid overnight risk.",
    "swing trading": "Swing trading holds positions for days to weeks to capture intermediate price swings.",
    "scalping": "Scalping seeks many small profits from tiny price moves, often with high frequency and tight stops.",
    "position trading": "Position trading holds for weeks to months based on major trends or macro themes.",
    "intraday trading": "Intraday trading focuses on moves within one trading day using shorter timeframes.",
    "overnight risk": "Overnight risk is exposure to price gaps or news while markets are closed.",
    "weekend gap risk": "Weekend gap risk affects markets closed over weekends when news can shift prices at reopen.",
    "news trading": "News trading reacts to economic releases, earnings, or geopolitical headlines for volatility.",
    "economic calendar": "An economic calendar lists scheduled data releases like jobs, inflation, and central bank decisions.",
    "interest rate": "Interest rates influence borrowing costs, currency values, and equity valuations.",
    "central bank": "A central bank sets monetary policy and can move markets through rate and liquidity decisions.",
    "Federal Reserve": "The Federal Reserve is the US central bank; its policy affects global liquidity and risk appetite.",
    "inflation": "Inflation erodes purchasing power; rising inflation often pressures bonds and changes rate expectations.",
    "CPI": "Consumer Price Index measures inflation in a basket of goods and services.",
    "GDP": "Gross Domestic Product measures total economic output and growth over a period.",
    "unemployment rate": "Unemployment shows labor market health and can influence consumer spending and policy.",
    "nonfarm payrolls": "NFP reports US job additions excluding farming and is a major forex and index mover.",
    "FOMC": "The Federal Open Market Committee sets US interest rate policy and publishes meeting statements.",
    "quantitative easing": "QE is central bank asset purchases to inject liquidity and lower long-term rates.",
    "yield curve": "The yield curve plots bond yields by maturity; inversion sometimes signals recession concerns.",
    "bond market": "The bond market trades government and corporate debt and affects rates across the economy.",
    "stock market": "The stock market is where shares of public companies are bought and sold.",
    "index": "An index tracks a basket of stocks or assets, such as the S&P 500 or Nasdaq.",
    "ETF": "An exchange-traded fund tracks an index or theme and trades like a stock on an exchange.",
    "mutual fund": "A mutual fund pools investor money into a managed portfolio priced once daily.",
    "sector rotation": "Sector rotation shifts capital among industries as the economic cycle evolves.",
    "blue chip stock": "Blue chips are large, established companies with stable earnings and liquidity.",
    "penny stock": "Penny stocks trade at low prices, often with thin liquidity and higher manipulation risk.",
    "growth stock": "Growth stocks reinvest earnings for expansion and trade at higher valuation multiples.",
    "value stock": "Value stocks appear cheap relative to fundamentals like earnings, book value, or cash flow.",
    "dividend stock": "Dividend stocks pay regular income to shareholders from company profits.",
    "IPO": "An initial public offering is when a private company first sells shares to the public.",
    "secondary offering": "A secondary offering sells additional shares after the IPO, sometimes diluting existing holders.",
    "stock split": "A stock split increases share count and lowers price per share without changing total value.",
    "reverse split": "A reverse split reduces share count and raises price per share, often used to meet listing requirements.",
    "buyback": "A share buyback reduces shares outstanding and can support earnings per share.",
    "merger": "A merger combines two companies, often affecting shareholder value and sector dynamics.",
    "acquisition": "An acquisition is when one company buys another, sometimes at a premium to market price.",
    "forex market": "Forex is the global market for exchanging currencies, operating nearly 24 hours on weekdays.",
    "currency pair": "A currency pair quotes one currency against another, such as EUR/USD.",
    "base currency": "In a pair, the base currency is the first listed and equals one unit in the quote.",
    "quote currency": "The quote currency shows how much one unit of base currency costs.",
    "major pairs": "Major forex pairs include USD with EUR, JPY, GBP, CHF, CAD, AUD, or NZD.",
    "cross pair": "A cross pair excludes USD, such as EUR/GBP or AUD/JPY.",
    "carry trade": "A carry trade borrows a low-yield currency to buy a higher-yield currency for interest differential.",
    "swap rate": "A swap rate is overnight interest credited or debited for holding a forex or CFD position.",
    "cryptocurrency": "Cryptocurrency is digital value secured by cryptography and often traded on blockchain networks.",
    "Bitcoin": "Bitcoin is the first major decentralized cryptocurrency, often viewed as digital store of value.",
    "Ethereum": "Ethereum is a blockchain platform supporting smart contracts and many decentralized applications.",
    "altcoin": "An altcoin is any cryptocurrency other than Bitcoin.",
    "stablecoin": "A stablecoin pegs value to fiat or assets to reduce price volatility.",
    "blockchain": "A blockchain is a distributed ledger recording transactions across many nodes.",
    "wallet": "A crypto wallet stores keys used to send and receive digital assets.",
    "exchange wallet": "Exchange wallets hold assets on a platform; users rely on the exchange's custody.",
    "cold storage": "Cold storage keeps crypto offline to reduce hacking risk.",
    "gas fees": "Gas fees pay for computation on networks like Ethereum when executing transactions.",
    "market cap in crypto": "Crypto market cap equals coin price times circulating supply.",
    "halving": "Bitcoin halving cuts miner block rewards roughly every four years, reducing new supply.",
    "DeFi": "Decentralized finance offers lending, trading, and yield without traditional intermediaries on-chain.",
    "NFT": "A non-fungible token represents unique digital ownership recorded on a blockchain.",
    "futures contract": "A futures contract obligates buying or selling an asset at a set price on a future date.",
    "forward contract": "A forward is a customized OTC agreement to exchange an asset at a future date and price.",
    "options contract": "An option gives the right, not obligation, to buy or sell at a strike price by expiry.",
    "call option": "A call option profits when the underlying price rises above the strike plus premium paid.",
    "put option": "A put option profits when the underlying price falls below the strike minus premium paid.",
    "strike price": "The strike is the price at which an option can be exercised.",
    "option premium": "Premium is the price paid upfront for an option contract.",
    "expiration date": "Expiration is when an option contract expires and becomes worthless if out of the money.",
    "in-the-money option": "An ITM option has intrinsic value because the strike is favorable versus spot price.",
    "out-of-the-money option": "An OTM option has no intrinsic value because spot has not reached a profitable strike.",
    "at-the-money option": "An ATM option has strike near current price with mostly time value.",
    "time decay": "Time decay erodes option value as expiration approaches, especially for OTM contracts.",
    "theta": "Theta measures how much option value decreases per day from time decay.",
    "delta": "Delta estimates option price change for a one-point move in the underlying.",
    "gamma": "Gamma measures how fast delta changes as the underlying moves.",
    "vega": "Vega measures sensitivity to implied volatility changes.",
    "covered call": "A covered call sells calls against owned stock to earn premium with capped upside.",
    "protective put": "A protective put buys downside insurance while keeping upside in owned stock.",
    "straddle": "A straddle buys call and put at the same strike to profit from large moves either direction.",
    "strangle": "A strangle buys OTM call and put to profit from volatility at lower cost than a straddle.",
    "iron condor": "An iron condor sells a range-bound spread to collect premium when price stays between strikes.",
    "spread trading": "Spread trading combines long and short legs to reduce cost and define risk.",
    "CFD": "A contract for difference pays the difference between entry and exit without owning the underlying.",
    "commodity": "Commodities are raw materials like oil, gold, and wheat traded on global markets.",
    "gold trading": "Gold is often viewed as a hedge against inflation and uncertainty.",
    "crude oil trading": "Oil prices react to supply, demand, geopolitics, and inventory data.",
    "natural gas futures": "Natural gas futures trade seasonal demand and storage levels with high volatility.",
    "index futures": "Index futures track benchmark equity indices for hedging or speculation.",
    "contango": "Contango occurs when futures price is above spot, common in some commodity curves.",
    "backwardation": "Backwardation occurs when futures trade below spot, often signaling tight supply.",
    "rollover": "Rollover moves a futures position to the next contract month before expiry.",
    "settlement price": "Settlement price is the official closing value used to mark futures accounts daily.",
    "mark-to-market": "Mark-to-market updates account equity daily based on current market prices.",
    "arbitrage": "Arbitrage exploits small price differences across markets for low-risk profit.",
    "statistical arbitrage": "Stat arb uses models to trade mean reversion between related instruments.",
    "pairs trading": "Pairs trading goes long one asset and short a correlated peer when spread diverges.",
    "mean reversion": "Mean reversion assumes prices return toward average after extreme moves.",
    "momentum trading": "Momentum trading follows strong trends, buying strength and selling weakness.",
    "trend following": "Trend following rides sustained moves using rules like breakouts or moving averages.",
    "contrarian trading": "Contrarian trading fades extreme sentiment, betting crowds are wrong at extremes.",
    "breakout trading": "Breakout trading enters when price clears key levels with confirming volume.",
    "range trading": "Range trading buys support and sells resistance inside a defined channel.",
    "grid trading": "Grid trading places layered buy and sell orders at fixed intervals within a range.",
    "dollar-cost averaging": "DCA invests fixed amounts regularly, reducing timing risk over time.",
    "tax-loss harvesting": "Tax-loss harvesting sells losers to offset gains, subject to local tax rules.",
    "wash sale rule": "Wash sale rules may disallow loss deductions if you repurchase substantially identical securities too soon.",
    "capital gains tax": "Capital gains tax applies to profit when selling assets above purchase cost.",
    "pattern day trader rule": "In the US, PDT rules require $25,000 minimum equity for frequent day trading in margin accounts.",
    "SEC": "The SEC regulates US securities markets and protects investors.",
    "FINRA": "FINRA oversees broker-dealers and enforces conduct standards in the US.",
    "KYC": "Know Your Customer rules require brokers to verify client identity before account opening.",
    "AML": "Anti-money laundering rules require monitoring suspicious financial activity.",
    "trading psychology": "Trading psychology manages emotions like fear, greed, and overconfidence that drive mistakes.",
    "FOMO": "Fear of missing out pushes traders into late entries without proper setup validation.",
    "revenge trading": "Revenge trading increases size or frequency after losses to recover quickly, often worsening results.",
    "overtrading": "Overtrading takes too many low-quality setups, increasing fees and emotional fatigue.",
    "discipline": "Discipline means following your plan even when emotions push for deviation.",
    "trading plan": "A trading plan defines markets, setups, risk, and rules before capital is at risk.",
    "trading journal": "A trading journal records entries, exits, reasons, and emotions to improve over time.",
    "edge": "An edge is a repeatable advantage that produces positive expectancy over many trades.",
    "expectancy": "Expectancy is average profit per trade after wins, losses, and position sizing.",
    "win rate": "Win rate is percentage of trades that are profitable, only meaningful with average win and loss size.",
    "profit factor": "Profit factor is gross profits divided by gross losses; above 1 indicates net profitability.",
    "maximum adverse excursion": "MAE tracks the worst drawdown during a trade before exit.",
    "maximum favorable excursion": "MFE tracks the best unrealized profit during a trade before exit.",
    "R-multiple": "An R-multiple expresses profit or loss as multiples of initial risk per trade.",
    "stop hunting": "Stop hunting is when price briefly moves to trigger clustered stops before reversing.",
    "whale": "A whale is a large holder whose trades can move thin markets significantly.",
    "dark pool": "Dark pools are private venues where large orders execute with less public visibility.",
    "after-hours trading": "After-hours trading occurs outside regular session times with often lower liquidity.",
    "pre-market trading": "Pre-market trading happens before the official open, reacting to overnight news.",
    "regular trading hours": "Regular hours are standard exchange session times with highest liquidity.",
    "circuit breaker": "Circuit breakers halt trading temporarily after extreme index moves to calm markets.",
    "limit up limit down": "LULD bands restrict how far stocks can move in a short period during volatility.",
    "halted stock": "A trading halt pauses a stock due to news pending, volatility, or regulatory reasons.",
    "dividend capture": "Dividend capture buys before ex-date for the dividend, though price often adjusts accordingly.",
    "spin-off": "A spin-off creates a separate public company from a division of a parent firm.",
    "special dividend": "A special dividend is a one-time payout beyond regular dividend schedule.",
    "rights offering": "A rights offering lets existing shareholders buy additional shares, often at a discount.",
    "warrant": "A warrant gives the right to buy stock at a set price before expiration, similar to a long-dated call.",
    "convertible bond": "A convertible bond pays interest but can convert into stock under specified terms.",
    "preferred stock": "Preferred stock pays fixed dividends and has priority over common stock in some payouts.",
    "common stock": "Common stock represents ownership with voting rights and variable dividends if any.",
    "ADR": "An American Depositary Receipt lets US investors trade foreign shares in dollars on US exchanges.",
    "dual listing": "Dual listing trades the same company on two exchanges, sometimes creating small price gaps.",
    "market order protection": "Order protection rules aim to execute retail orders at the best displayed price.",
    "payment for order flow": "PFOF routes orders to market makers who may pay brokers for order flow.",
    "direct market access": "DMA lets advanced traders send orders directly to exchanges or ECNs.",
    "smart order routing": "Smart routing splits orders across venues to seek best price and liquidity.",
    "partial fill": "A partial fill executes only part of an order when full size is not available at desired price.",
    "all-or-none order": "An AON order fills completely or not at all.",
    "iceberg order": "An iceberg shows only part of size publicly while hiding the rest.",
    "VIX": "The VIX measures expected S&P 500 volatility and is often called the fear gauge.",
    "DXY": "The US Dollar Index tracks USD against a basket of major currencies.",
    "safe haven asset": "Safe havens like gold or certain bonds attract flows during risk-off periods.",
    "risk-on risk-off": "Risk-on favors equities and high beta assets; risk-off favors bonds, USD, and defensive names.",
    "emerging markets": "Emerging markets offer growth potential with higher political and currency risk.",
    "developed markets": "Developed markets have mature institutions, deeper liquidity, and lower sovereign risk.",
    "sovereign debt": "Sovereign debt is government borrowing; yields reflect creditworthiness and rate expectations.",
    "credit rating": "Credit ratings grade borrower default risk from agencies like Moody's or S&P.",
    "yield spread": "Yield spread is the difference between two bond yields, often signaling risk appetite.",
    "real interest rate": "Real rate subtracts inflation from nominal rate, affecting investment decisions.",
    "monetary tightening": "Tightening raises rates or reduces liquidity to cool inflation.",
    "monetary easing": "Easing lowers rates or adds liquidity to stimulate growth.",
    "stagflation": "Stagflation combines slow growth with high inflation, challenging traditional asset correlations.",
    "recession": "A recession is a broad economic decline, often hurting cyclical stocks and credit.",
    "soft landing": "A soft landing slows inflation without severe recession, a favorable macro outcome.",
    "hard landing": "A hard landing means recession follows aggressive tightening to control inflation.",
    "fiscal policy": "Fiscal policy uses government spending and taxation to influence the economy.",
    "trade deficit": "A trade deficit imports exceed exports, affecting currency and political debate.",
    "current account": "The current account includes trade balance and international income transfers.",
    "capital flight": "Capital flight is rapid outflow of investment from a country during stress.",
    "devaluation": "Devaluation officially lowers a currency's value versus others or gold.",
    "peg": "A currency peg fixes exchange rate to another currency or basket with central bank support.",
    "intervention": "Central bank intervention buys or sells currency to influence exchange rates.",
    "reserve currency": "A reserve currency, like USD, is widely held by central banks for trade and reserves.",
    "balance of payments": "Balance of payments records all economic transactions between a country and the world.",
    "Purchasing Managers Index": "PMI surveys manufacturing or services activity; above 50 often signals expansion.",
    "Consumer Confidence Index": "Consumer confidence gauges household optimism about jobs and spending.",
    "Retail sales data": "Retail sales measure consumer spending and can move growth-sensitive assets.",
    "housing starts": "Housing starts track new residential construction, a leading economic indicator.",
    "industrial production": "Industrial production measures output of factories, mines, and utilities.",
    "trade balance": "Trade balance is exports minus imports and affects currency and GDP components.",
    "leading indicator": "Leading indicators change before the broader economy, helping forecast cycles.",
    "lagging indicator": "Lagging indicators confirm trends after they have started, like unemployment in downturns.",
    "coincident indicator": "Coincident indicators move with the economy, such as industrial production.",
    "seasonality": "Seasonality is recurring calendar patterns, like year-end rallies or commodity harvest cycles.",
    "January effect": "The January effect is the historical tendency for small caps to outperform early in the year.",
    "sell in May": "Sell in May refers to weaker summer seasonality in some equity markets.",
    "Santa Claus rally": "The Santa Claus rally describes late-December strength in equities in some years.",
    "quarter end rebalancing": "Quarter end rebalancing can create predictable flows as funds adjust holdings.",
    "options expiration": "Monthly or weekly options expiration can increase volatility as dealers adjust hedges.",
    "triple witching": "Triple witching occurs when stock index futures, options, and single-stock options expire together.",
    "earnings season": "Earnings season clusters quarterly reports and drives stock-specific volatility.",
    "guidance revision": "Guidance revision updates prior forecasts and can move prices sharply.",
    "whisper number": "Whisper numbers are unofficial earnings expectations beyond published analyst estimates.",
    "beat and raise": "Beat and raise means results exceed estimates and outlook improves, often bullish.",
    "miss and lower": "Miss and lower means results fall short and guidance weakens, often bearish.",
    "conference call": "An earnings call lets management explain results and answer analyst questions.",
    "10-K report": "A 10-K is an annual SEC filing with comprehensive company financials.",
    "10-Q report": "A 10-Q is a quarterly SEC filing with updated financial statements.",
    "8-K filing": "An 8-K reports major events like leadership changes, acquisitions, or restatements.",
    "insider form 4": "Form 4 reports insider buys and sells within two business days in the US.",
    "13F filing": "13F shows quarterly holdings of large investment managers.",
    "short ratio": "Short ratio divides short interest by average daily volume, estimating days to cover.",
    "days to cover": "Days to cover estimates how long shorts need to repurchase shares at average volume.",
    "borrow rate": "Borrow rate is the fee to borrow shares for short selling; high rates signal scarce supply.",
    "hard to borrow": "Hard-to-borrow stocks have limited lendable shares, increasing short costs.",
    "locate requirement": "Brokers require locates to confirm shares can be borrowed before short sale.",
    "uptick rule": "The uptick rule restricts short selling only on an uptick in some jurisdictions.",
    "regulation SHO": "Reg SHO includes close-out requirements to reduce fails in short selling.",
    "market manipulation": "Manipulation illegally distorts price through false information or coordinated schemes.",
    "pump and dump": "Pump and dump artificially inflates price through hype then sells into retail buyers.",
    "spoofing": "Spoofing places fake orders to mislead others about supply or demand.",
    "front running": "Front running trades ahead of known client orders for unfair advantage.",
    "insider information": "Trading on material nonpublic information is illegal in regulated markets.",
    "compliance": "Compliance ensures trading activity follows laws, exchange rules, and firm policies.",
    "best execution": "Best execution requires brokers to seek favorable price, speed, and likelihood of fill.",
    "suitability": "Suitability means recommendations fit client risk tolerance and objectives.",
    "accredited investor": "Accredited investors meet wealth or income thresholds for certain private offerings.",
    "risk disclosure": "Risk disclosure documents explain potential losses before trading complex products.",
    "leverage disclosure": "Brokers must explain how leverage magnifies losses as well as gains.",
    "margin interest": "Margin interest is the cost of borrowing funds from a broker.",
    "free riding": "Free riding uses unsettled funds improperly before payment clears.",
    "good faith violation": "A good faith violation buys with unsettled funds then sells before settlement funds arrive.",
    "settlement violation": "Settlement violations occur when accounts lack funds to cover purchases on due date.",
    "cash account": "A cash account only trades with settled funds, limiting some strategies.",
    "margin account": "A margin account allows borrowing and short selling subject to requirements.",
    "portfolio margin": "Portfolio margin uses risk-based models and may allow higher leverage for hedged portfolios.",
    "Reg T margin": "Reg T sets initial margin requirements for US securities on margin accounts.",
    "SPAN margin": "SPAN margin models futures and options portfolio risk for margin calculation.",
    "cross margining": "Cross margining offsets risk across related positions in one account.",
    "isolated margin": "Isolated margin limits loss to collateral assigned to one position, common in crypto.",
    "liquidation": "Liquidation forcibly closes positions when margin is insufficient to cover losses.",
    "bankruptcy remote": "Bankruptcy remote structures protect client assets if a broker fails, depending on jurisdiction.",
    "SIPC protection": "SIPC may protect US brokerage cash and securities if a member firm fails, within limits.",
    "FDIC insurance": "FDIC insures bank deposits in the US, not securities losses.",
    "custody": "Custody is safekeeping of client assets separate from broker operating funds when rules require.",
    "rehypothecation": "Rehypothecation lets brokers reuse pledged collateral under certain agreements.",
    "segregated account": "Segregated accounts keep client funds separate from firm money.",
    "prime brokerage": "Prime brokers serve institutions with lending, clearing, and multi-asset services.",
    "prime broker": "A prime broker provides financing and operational support to hedge funds.",
    "fundamental screener": "Screeners filter stocks by metrics like P/E, revenue growth, or debt ratios.",
    "technical screener": "Technical screeners filter by indicators, patterns, or price and volume conditions.",
    "watchlist": "A watchlist tracks symbols you monitor for setups without holding positions.",
    "alert": "Price or indicator alerts notify traders when conditions are met.",
    "hotkey trading": "Hotkeys execute orders quickly using keyboard shortcuts.",
    "one-click trading": "One-click trading sends orders with a single action, requiring careful setup.",
    "OCO order": "One-cancels-other links two orders so filling one cancels the other.",
    "IF-DONE order": "IF-DONE triggers a second order only after the first order fills.",
    "scaling in": "Scaling in adds to a position in pieces as confirmation builds.",
    "scaling out": "Scaling out exits a position in pieces to lock profits while leaving a runner.",
    "pyramiding": "Pyramiding adds to winning positions as trend continues, increasing exposure with profits.",
    "averaging down": "Averaging down adds to a losing position to lower average cost, increasing risk if wrong.",
    "averaging up": "Averaging up adds as price rises, confirming trend but raising average entry.",
    "breakeven stop": "Moving stop to breakeven protects capital after price moves favorably.",
    "time stop": "A time stop exits if price fails to move within a set period.",
    "volatility stop": "A volatility stop uses ATR or similar to place stops beyond normal noise.",
    "fixed stop": "A fixed stop exits at a predetermined price regardless of volatility.",
    "mental stop": "A mental stop is a planned exit level not placed on the platform, relying on discipline.",
    "hard stop": "A hard stop is an actual order resting in the market or broker system.",
    "gap stop risk": "Gap risk means price may jump past your stop level at the open.",
    "limit exit": "A limit exit targets a specific profit price but may not fill if price reverses quickly.",
    "market exit": "A market exit prioritizes immediate closure over exact price.",
    "partial profit taking": "Partial profit taking sells part of a position to reduce risk while staying exposed.",
    "trailing profit target": "A trailing profit target moves with price to capture extended trends.",
    "risk of ruin": "Risk of ruin estimates probability of losing entire capital given win rate and sizing.",
    "Kelly criterion": "Kelly formula suggests optimal bet size based on edge and odds, often scaled down in practice.",
    "fixed fractional sizing": "Fixed fractional sizing risks a constant percentage of equity per trade.",
    "volatility targeting": "Volatility targeting adjusts position size inversely to recent market volatility.",
    "maximum drawdown limit": "A max drawdown limit stops trading after account falls by a preset amount.",
    "daily loss limit": "A daily loss limit halts trading after reaching maximum acceptable loss for the day.",
    "trade frequency limit": "Limiting trades per day prevents overtrading during emotional periods.",
    "cooldown period": "A cooldown pauses trading after losses or rule breaks to reset focus.",
    "pre-market checklist": "A checklist confirms market context, levels, and risk before the session starts.",
    "post-market review": "Post-market review analyzes trades, mistakes, and market behavior after close.",
    "benchmark": "A benchmark like the S&P 500 measures whether strategy performance beats the market.",
    "tracking error": "Tracking error measures deviation of portfolio returns from its benchmark.",
    "information ratio": "Information ratio compares active return to tracking error.",
    "Sortino ratio": "Sortino ratio focuses on downside volatility rather than total volatility.",
    "Calmar ratio": "Calmar ratio compares annual return to maximum drawdown.",
    "Monte Carlo simulation": "Monte Carlo simulates many random trade sequences to estimate risk of ruin and drawdowns.",
    "walk-forward analysis": "Walk-forward optimizes on one period and tests on the next to reduce overfitting.",
    "overfitting": "Overfitting tunes a strategy too closely to past data, failing on new data.",
    "curve fitting": "Curve fitting adjusts parameters until history looks perfect but live performance degrades.",
    "out-of-sample testing": "Out-of-sample testing validates strategy on data not used during development.",
    "in-sample data": "In-sample data is used to build and tune the strategy.",
    "survivorship bias": "Survivorship bias ignores delisted failures, overstating historical returns.",
    "lookahead bias": "Lookahead bias accidentally uses future information unavailable at decision time.",
    "data snooping bias": "Data snooping tests many ideas on same data until one looks good by chance.",
    "transaction costs": "Transaction costs include commissions, spreads, slippage, and taxes.",
    "turnover": "Turnover measures how often a portfolio trades; high turnover raises costs.",
    "capacity": "Strategy capacity is how much capital can trade before returns degrade from market impact.",
    "market impact": "Market impact is price movement caused by your own order size.",
    "participation rate": "Participation rate limits order size as fraction of market volume to reduce impact.",
    "TWAP": "Time-weighted average price execution spreads orders evenly across a time window.",
    "VWAP execution": "VWAP algorithms target average price weighted by volume during the session.",
    "implementation shortfall": "Implementation shortfall measures difference between decision price and actual fill.",
    "latency": "Latency is delay between signal, order send, and exchange acknowledgment.",
    "co-location": "Co-location places servers near exchange matching engines to reduce latency.",
    "tick data": "Tick data records every price change or trade for granular analysis.",
    "OHLC data": "OHLC summarizes open, high, low, and close for each bar period.",
    "timeframe": "Timeframe is bar length such as 1 minute, 1 hour, or daily chart.",
    "multi-timeframe analysis": "Multi-timeframe analysis aligns higher timeframe trend with lower timeframe entries.",
    "higher timeframe bias": "Higher timeframe bias uses daily or weekly trend to filter intraday trades.",
    "confluence": "Confluence occurs when multiple signals align at the same price zone.",
    "price action": "Price action reads raw candle and structure without heavy indicator reliance.",
    "market structure": "Market structure describes swing highs and lows defining trend and key levels.",
    "higher high": "A higher high confirms bullish structure when peaks rise sequentially.",
    "lower low": "A lower low confirms bearish structure when troughs fall sequentially.",
    "change of character": "Change of character signals potential trend shift when structure breaks prior pattern.",
    "break of structure": "Break of structure occurs when price violates a key swing, suggesting continuation or reversal.",
    "fair value gap": "A fair value gap is a three-candle imbalance zone price may revisit.",
    "order block": "An order block is a zone where institutional orders may have originated before a strong move.",
    "liquidity pool": "A liquidity pool clusters stop orders above highs or below lows that price may seek.",
    "liquidity sweep": "A liquidity sweep runs stops beyond a level then reverses, trapping breakout traders.",
    "inducement": "Inducement lures traders into poor entries before the intended move.",
    "smart money concept": "Smart money concepts focus on institutional behavior, liquidity, and structure.",
    "supply zone": "A supply zone is an area where selling pressure previously caused price to fall.",
    "demand zone": "A demand zone is an area where buying pressure previously caused price to rise.",
    "imbalance": "Imbalance is aggressive one-sided trading leaving inefficient price areas.",
    "efficient market hypothesis": "EMH argues prices reflect all available information, challenging persistent edges.",
    "random walk": "Random walk theory suggests short-term price changes are unpredictable.",
    "behavioral finance": "Behavioral finance studies cognitive biases affecting investor decisions.",
    "loss aversion": "Loss aversion makes losses feel worse than equivalent gains, causing poor risk decisions.",
    "confirmation bias": "Confirmation bias favors information that supports existing beliefs.",
    "anchoring bias": "Anchoring fixates on irrelevant reference prices like purchase cost or prior high.",
    "recency bias": "Recency bias overweight recent events when forecasting future outcomes.",
    "gambler's fallacy": "Gambler's fallacy wrongly assumes independent outcomes must balance soon.",
    "disposition effect": "Disposition effect sells winners too early and holds losers too long.",
    "herding": "Herding follows crowd behavior, amplifying bubbles and crashes.",
    "market bubble": "A bubble is unsustainable price rise detached from fundamentals.",
    "crash": "A crash is a sudden severe market decline over a short period.",
    "black swan event": "A black swan is a rare, high-impact event largely unforeseen by models.",
    "tail risk": "Tail risk is extreme outcome probability in the far ends of the distribution.",
    "fat tails": "Fat tails mean extreme moves occur more often than normal distribution predicts.",
    "value at risk": "VaR estimates maximum expected loss over a period at a confidence level.",
    "conditional VaR": "CVaR averages losses beyond the VaR threshold, capturing tail severity.",
    "stress testing": "Stress testing simulates portfolio performance under severe hypothetical scenarios.",
    "scenario analysis": "Scenario analysis evaluates outcomes under specific macro or market assumptions.",
    "correlation breakdown": "Correlation breakdown happens when diversifiers move together in crises.",
    "flight to quality": "Flight to quality moves capital into safer assets during uncertainty.",
    "liquidity crunch": "A liquidity crunch makes it hard to trade without large price impact.",
    "margin debt": "Margin debt tracks borrowed funds in brokerage accounts and can signal risk appetite.",
    "investor sentiment survey": "Sentiment surveys gauge bullish or bearish outlook among participants.",
    "AAII sentiment": "AAII survey tracks individual investor bullish, bearish, and neutral percentages.",
    "CNN fear and greed": "CNN's index blends seven indicators into a single sentiment score.",
    "COT report": "Commitments of Traders report shows positioning of commercial, non-commercial, and retail traders.",
    "commercial hedger": "Commercial hedgers use futures to offset business risk, like producers or airlines.",
    "large speculator": "Large speculators are major non-commercial traders often followed in COT analysis.",
    "retail sentiment": "Retail sentiment aggregates small trader positioning, sometimes used as contrarian input.",
    "open drive": "An open drive is strong directional move from the session open with little pullback.",
    "opening range": "Opening range is high-low of first minutes or hour used for breakout strategies.",
    "initial balance": "Initial balance in market profile is first period range setting context for the day.",
    "value area": "Value area contains price range where most volume traded during a session.",
    "point of control": "Point of control is the price with highest traded volume in a profile.",
    "single print": "Single prints are thin profile areas suggesting fast, imbalanced moves.",
    "excess": "Excess is tail rejection in profile showing strong rejection at extremes.",
    "poor high": "Poor high lacks excess at top, suggesting unfinished business above.",
    "poor low": "Poor low lacks excess at bottom, suggesting unfinished business below.",
    "balanced market": "Balanced market rotates within value with two-sided trade.",
    "imbalanced market": "Imbalanced market trends directionally away from value.",
    "responsive activity": "Responsive activity fades moves back toward value in balance.",
    "initiative activity": "Initiative activity drives price away from value in trend.",
    "auction market theory": "Auction theory views price as continuous search for fair value through trade.",
    "Wyckoff method": "Wyckoff analyzes accumulation, markup, distribution, and markdown phases.",
    "accumulation phase": "Accumulation is sideways basing where smart money buys before markup.",
    "markup phase": "Markup is rising trend after accumulation completes.",
    "distribution phase": "Distribution is topping process where smart money sells into strength.",
    "markdown phase": "Markdown is declining trend after distribution completes.",
    "spring": "A Wyckoff spring briefly breaks support to shake out sellers before rally.",
    "upthrust": "An upthrust briefly breaks resistance to trap buyers before decline.",
    "sign of strength": "Sign of strength is bullish price/volume action leaving accumulation.",
    "sign of weakness": "Sign of weakness is bearish action leaving distribution.",
    "Elliott Wave theory": "Elliott Wave proposes markets move in fractal five-wave impulses and three-wave corrections.",
    "impulse wave": "Impulse waves follow trend in five sub-waves.",
    "corrective wave": "Corrective waves retrace trend in three sub-waves.",
    "wave count": "Wave count labels current position in proposed Elliott structure.",
    "Harmonic pattern": "Harmonic patterns use Fibonacci ratios to identify potential reversal zones.",
    "Gartley pattern": "Gartley is a harmonic pattern with specific Fibonacci retracement and extension ratios.",
    "Bat pattern": "Bat pattern is a harmonic structure with deep retracement and defined PRZ.",
    "Butterfly pattern": "Butterfly extends beyond prior swing with precise Fibonacci alignment.",
    "Crab pattern": "Crab is an extreme harmonic pattern with deep extension ratios.",
    "ABCD pattern": "ABCD uses equal legs or Fib ratios to project reversal points.",
    "Ichimoku cloud": "Ichimoku combines multiple lines and cloud to show trend, support, and momentum.",
    "Tenkan-sen": "Tenkan-sen is Ichimoku conversion line, short-term equilibrium.",
    "Kijun-sen": "Kijun-sen is base line showing medium-term equilibrium.",
    "Senkou Span A": "Senkou Span A forms one cloud boundary from midpoints of Tenkan and Kijun, shifted forward.",
    "Senkou Span B": "Senkou Span B forms other cloud boundary from long-period midpoint, shifted forward.",
    "Chikou Span": "Chikou Span plots closing price shifted back for momentum confirmation.",
    "Kumo breakout": "Kumo breakout occurs when price clears the Ichimoku cloud.",
    "Parabolic SAR": "Parabolic SAR places trailing dots above or below price to suggest trend and stops.",
    "Donchian channel": "Donchian channels plot highest high and lowest low over N periods for breakouts.",
    "Keltner channel": "Keltner channels use ATR around EMA to define volatility bands.",
    "Standard deviation channel": "Std dev channels plot bands at fixed standard deviations from a linear regression line.",
    "linear regression": "Linear regression fits a trend line to price for mean and deviation analysis.",
    "Z-score": "Z-score measures how many standard deviations price is from mean, useful in pairs trading.",
    "Hurst exponent": "Hurst exponent estimates whether series is trending, random, or mean reverting.",
    "autocorrelation": "Autocorrelation measures relationship between series and its lagged values.",
    "cointegration": "Cointegration means two non-stationary series share long-run equilibrium relationship.",
    "stationarity": "Stationary series have stable statistical properties over time, important for modeling.",
    "ARIMA model": "ARIMA models time series using autoregression, differencing, and moving averages.",
    "GARCH model": "GARCH models changing volatility clusters in financial returns.",
    "machine learning in trading": "ML in trading uses data patterns for signals but risks overfitting without robust validation.",
    "feature engineering": "Feature engineering creates predictive inputs like returns, volatility, or sentiment scores.",
    "labeling trades": "Labeling defines target outcomes for supervised learning, such as next-bar direction.",
    "train-test split": "Train-test split separates data for model training versus evaluation.",
    "cross-validation": "Cross-validation rotates train and validation folds to assess model stability.",
    "ensemble model": "Ensemble combines multiple models to improve robustness.",
    "reinforcement learning trading": "RL trading learns policies through reward signals from simulated or live environments.",
    "sentiment analysis": "Sentiment analysis scores news or social text for bullish or bearish tone.",
    "alternative data": "Alternative data includes satellite imagery, web traffic, or credit card trends for edge.",
    "on-chain analysis": "On-chain analysis studies blockchain metrics like active addresses and exchange flows.",
    "exchange inflow": "Large exchange inflows may signal potential selling pressure for crypto assets.",
    "exchange outflow": "Exchange outflows may indicate moving coins to cold storage, reducing sell supply.",
    "hash rate": "Hash rate measures mining power on proof-of-work networks, reflecting security and miner activity.",
    "network difficulty": "Difficulty adjusts mining challenge to maintain block time targets.",
    "proof of stake": "Proof of stake selects validators by staked coins rather than mining power.",
    "staking yield": "Staking yield rewards locking coins to secure proof-of-stake networks.",
    "yield farming": "Yield farming seeks returns by providing liquidity to DeFi protocols.",
    "impermanent loss": "Impermanent loss occurs when LP token value diverges from simply holding assets.",
    "liquidity pool token": "LP tokens represent share of a decentralized liquidity pool.",
    "automated market maker": "AMMs price trades using formulas and pool ratios instead of traditional order books.",
    "slippage in DeFi": "DeFi slippage worsens on low liquidity pools or large swaps.",
    "MEV": "Maximal extractable value is profit from reordering or inserting transactions in blocks.",
    "flash loan": "Flash loans borrow uncollateralized if repaid within same blockchain transaction.",
    "token unlock": "Token unlock releases previously locked supply, potentially increasing sell pressure.",
    "vesting schedule": "Vesting gradually releases team or investor tokens over time.",
    "airdrop": "Airdrop distributes free tokens to wallets for promotion or decentralization.",
    "hard fork": "Hard fork splits blockchain into incompatible chains with separate histories.",
    "soft fork": "Soft fork upgrades rules while remaining backward compatible with old nodes.",
    "Layer 2 scaling": "Layer 2 processes transactions off main chain to reduce fees and congestion.",
    "rollup": "Rollups batch transactions on L2 and post proofs or data to L1.",
    "bridge risk": "Cross-chain bridges can fail or be hacked, risking bridged assets.",
    "smart contract risk": "Smart contract bugs or exploits can drain DeFi protocols.",
    "rug pull": "Rug pull is when developers abandon project and remove liquidity illegally.",
    "KYC in crypto": "Crypto exchanges may require KYC for fiat ramps and compliance.",
    "cold wallet security": "Use hardware wallets and seed phrase backup offline for long-term crypto storage.",
    "seed phrase": "Seed phrase recovers wallet access; never share it with anyone.",
    "two-factor authentication": "2FA adds security layer beyond password for exchange accounts.",
    "phishing in trading": "Phishing uses fake login pages to steal credentials; verify URLs carefully.",
    "SIM swap attack": "SIM swap hijacks phone number to bypass SMS two-factor authentication.",
    "API key security": "Restrict trading API keys by IP and disable withdrawal permissions when possible.",
    "bot trading risk": "Automated bots can malfunction or overtrade if not monitored and capped.",
    "kill switch": "Kill switch halts all automated trading instantly during anomalies.",
    "max position limit": "Max position limit caps exposure per symbol or sector.",
    "exposure limit": "Exposure limit restricts total capital at risk across open trades.",
    "sector exposure": "Sector exposure tracks concentration in industries like tech or energy.",
    "currency exposure": "Currency exposure measures profit sensitivity to FX moves in international holdings.",
    "delta hedging": "Delta hedging adjusts underlying position to neutralize option delta changes.",
    "gamma scalping": "Gamma scalping trades underlying around long gamma option positions.",
    "volatility trading": "Volatility trading profits from changes in implied or realized volatility.",
    "volatility smile": "Volatility smile shows IV varying by strike, common in equity options.",
    "volatility skew": "Skew shows higher IV for OTM puts than calls in many equity markets.",
    "term structure of volatility": "Term structure plots IV across expirations, reflecting near vs far uncertainty.",
    "VIX futures": "VIX futures trade expected future volatility index levels.",
    "volatility ETN": "Volatility ETNs track VIX-related indices with contango decay risks.",
    "dispersion trade": "Dispersion trades index volatility against single-stock volatility.",
    "calendar spread": "Calendar spread buys and sells options of same strike but different expirations.",
    "diagonal spread": "Diagonal spread uses different strikes and expirations for directional bias.",
    "vertical spread": "Vertical spread buys and sells same expiration options at different strikes.",
    "butterfly spread": "Butterfly combines vertical spreads for limited risk around a central strike.",
    "ratio spread": "Ratio spread uses unequal long and short legs, creating complex risk.",
    "synthetic long": "Synthetic long combines long call and short put at same strike to mimic stock.",
    "synthetic short": "Synthetic short combines short call and long put to mimic short stock.",
    "box spread": "Box spread combines bull and bear vertical spreads for arbitrage-like fixed payoff.",
    "pin risk": "Pin risk occurs when stock expires near short option strike, uncertain assignment.",
    "early assignment": "American options may be exercised early, especially deep ITM calls before dividends.",
    "assignment in options": "Assignment obligates short option writer to fulfill contract terms.",
    "exercise options": "Exercise uses option right to buy or sell at strike.",
    "European option": "European options exercise only at expiration.",
    "American option": "American options may exercise any time before expiration.",
    "LEAPS": "LEAPS are long-term equity options expiring more than a year out.",
    "weekly options": "Weekly options expire each week, offering short-term hedging and speculation.",
    "0DTE options": "Zero days to expiration options expire same day, extremely sensitive to intraday moves.",
    "options open interest by strike": "OI by strike shows where large positions cluster, potential support or resistance.",
    "max pain theory": "Max pain theory suggests price may gravitate toward strike where option holders lose most.",
    "gamma exposure": "Dealer gamma exposure influences how hedging flows amplify or dampen moves.",
    "dark short interest": "Some short interest is hidden in derivatives, not fully captured in stock SI alone.",
    "total return swap": "TRS exchanges asset total return for funding payments without full ownership transfer.",
    "CFD overnight fee": "CFDs charge overnight financing based on benchmark rate plus broker markup.",
    "spread betting": "Spread betting is tax-treated differently in UK; profit/loss per point movement.",
    "stamp duty": "UK stamp duty may apply to share purchases depending on venue and instrument.",
    "T+2 settlement legacy": "Many markets moved from T+2 to T+1 to reduce counterparty risk timing.",
    "central counterparty": "CCP stands between trades, mutualizing default risk among members.",
    "novation": "Novation replaces original counterparty with CCP as buyer to every seller and vice versa.",
    "variation margin": "Variation margin is daily cash transfer reflecting mark-to-market P&L on derivatives.",
    "initial margin futures": "Futures initial margin is performance bond covering potential adverse moves.",
    "span risk array": "SPAN uses scenarios to estimate worst plausible loss for margin.",
    "delivery in futures": "Physical delivery futures require actual commodity transfer at expiry if not closed.",
    "cash settlement futures": "Cash settled futures pay difference between entry and final index or price.",
    "mini contract": "Mini contracts are smaller notional futures or options for retail sizing.",
    "micro contract": "Micro contracts offer even smaller size for precise risk control.",
    "tick value": "Tick value is dollar change per minimum price move times contract multiplier.",
    "point value": "Point value is monetary change per one full index or price point.",
    "contract multiplier": "Multiplier converts index or price points into dollar value per contract.",
    "basis in futures": "Basis is spot minus futures price; convergence expected near expiry.",
    "cost of carry": "Cost of carry includes storage, financing, and dividends affecting futures pricing.",
    "convenience yield": "Convenience yield is non-monetary benefit of holding physical commodity.",
    "storage cost": "Storage cost affects commodity futures curve, especially energy and metals.",
    "seasonal spread": "Seasonal spreads trade calendar spreads based on recurring supply cycles.",
    "crack spread": "Crack spread reflects refining margin between crude and products.",
    "crush spread": "Crush spread reflects soybean processing margin into meal and oil.",
    "spark spread": "Spark spread measures power plant margin between electricity and fuel costs.",
    "freight rate impact": "Shipping costs affect commodity delivered prices globally.",
    "geopolitical risk premium": "Geopolitical events can add risk premium to oil, gold, and defense stocks.",
    "sanctions impact trading": "Sanctions restrict trade flows and can reroute commodity supply chains.",
    "embargo": "Embargo bans trade with specific countries, affecting commodity availability.",
    "tariff": "Tariffs tax imports and can shift supply chains and input costs.",
    "trade war": "Trade wars escalate tariffs and restrictions, disrupting global commerce.",
    "supply chain disruption": "Supply shocks can spike prices and volatility in affected goods.",
    "inventory report": "Inventory reports like EIA crude stocks move energy markets weekly.",
    "OPEC decision": "OPEC+ output decisions influence global oil supply expectations.",
    "production cut": "Production cuts reduce supply and can support commodity prices.",
    "strategic petroleum reserve": "SPR releases add supply buffers during energy crises.",
    "weather impact commodities": "Weather affects crops, nat gas demand, and renewable output forecasts.",
    "El Nino trading impact": "El Nino can alter crop yields and commodity prices regionally.",
    "crop report": "USDA crop reports update supply estimates for grains and soft commodities.",
    "coffee trading fundamentals": "Coffee prices react to Brazil weather, currency, and global demand.",
    "sugar trading fundamentals": "Sugar ties to ethanol policy, weather, and currency in Brazil and India.",
    "cotton trading": "Cotton responds to textile demand, harvest, and trade policy.",
    "lumber futures": "Lumber futures reflect housing demand and supply chain constraints.",
    "copper as economic indicator": "Copper demand links to construction and industry, nicknamed Dr. Copper.",
    "gold safe haven": "Gold often rises during inflation fears and geopolitical stress.",
    "silver industrial demand": "Silver combines monetary and industrial uses, more volatile than gold.",
    "platinum palladium": "Platinum group metals depend on auto catalyst demand and supply constraints.",
    "rare earth trading": "Rare earths are critical for tech and subject to supply concentration risk.",
    "carbon credits trading": "Carbon markets trade emissions allowances as climate policy tools.",
    "ESG investing": "ESG integrates environmental, social, and governance factors in investment decisions.",
    "green bond": "Green bonds finance environmentally beneficial projects.",
    "impact investing": "Impact investing seeks measurable social or environmental outcomes plus return.",
    "sin stock": "Sin stocks include tobacco, gambling, or alcohol, sometimes defensive.",
    "ESG exclusion": "Exclusion screens remove sectors like fossil fuels from portfolios.",
    "proxy voting": "Shareholders vote on governance via proxy during annual meetings.",
    "activist investor": "Activists push companies for strategic, financial, or governance changes.",
    "hostile takeover": "Hostile takeover pursues control without target board approval.",
    "poison pill": "Poison pill dilutes acquirer to discourage hostile takeover.",
    "golden parachute": "Golden parachute compensates executives heavily if company is acquired.",
    "due diligence": "Due diligence investigates financials and risks before major investment.",
    "fair value": "Fair value is estimated intrinsic worth based on models or comparables.",
    "discounted cash flow": "DCF values company by discounting projected future cash flows.",
    "terminal value": "Terminal value estimates cash flows beyond explicit forecast period in DCF.",
    "WACC": "Weighted average cost of capital discounts future flows using blended funding cost.",
    "free cash flow": "Free cash flow is operating cash minus capital expenditures.",
    "EBITDA": "EBITDA approximates operating earnings before interest, taxes, depreciation, and amortization.",
    "enterprise value": "Enterprise value is market cap plus net debt, representing total business value.",
    "EV/EBITDA multiple": "EV/EBITDA compares company value to operating earnings power.",
    "PEG ratio": "PEG adjusts P/E by growth rate to compare valuation across growth speeds.",
    "dividend discount model": "DDM values stock as present value of expected future dividends.",
    " Gordon growth model": "Gordon model assumes constant dividend growth rate in perpetuity.",
    "residual income model": "Residual income values stock using earnings above required return on book value.",
    "comparable company analysis": "Comps value firm using multiples of similar public companies.",
    "precedent transactions": "Precedent M&A deals provide valuation benchmarks for takeovers.",
    "sum-of-the-parts valuation": "SOTP values conglomerate by adding separate business segment values.",
    "asset-based valuation": "Asset-based valuation sums net asset value, common for holding companies.",
    "book value per share": "Book value per share is equity divided by shares outstanding.",
    "tangible book value": "Tangible book excludes intangible assets like goodwill.",
    "goodwill impairment": "Goodwill impairment writes down overpaid acquisition value, hitting earnings.",
    "working capital": "Working capital is current assets minus current liabilities, funding daily operations.",
    "current ratio": "Current ratio compares current assets to liabilities for liquidity health.",
    "quick ratio": "Quick ratio excludes inventory from assets for stricter liquidity test.",
    "debt-to-equity ratio": "D/E compares total debt to shareholder equity, signaling leverage risk.",
    "interest coverage ratio": "Interest coverage is EBIT divided by interest expense, showing debt service ability.",
    "return on equity": "ROE measures net income relative to shareholder equity.",
    "return on assets": "ROA measures net income relative to total assets.",
    "return on invested capital": "ROIC compares operating profit to invested capital for efficiency.",
    "gross margin": "Gross margin is revenue minus cost of goods sold, divided by revenue.",
    "operating margin": "Operating margin is operating income divided by revenue.",
    "net margin": "Net margin is net income divided by revenue.",
    "operating leverage": "Operating leverage magnifies profit changes when fixed costs are high.",
    "financial leverage": "Financial leverage uses debt to amplify equity returns and risk.",
    "dupont analysis": "DuPont breaks ROE into margin, turnover, and leverage components.",
    "inventory turnover": "Inventory turnover shows how quickly company sells and replaces stock.",
    "accounts receivable turnover": "Receivables turnover measures collection speed from customers.",
    "days sales outstanding": "DSO estimates average days to collect payment after sale.",
    "cash conversion cycle": "CCC tracks days to convert inventory and receivables into cash.",
    "capital expenditure": "CapEx is investment in long-term assets like plants and equipment.",
    "depreciation": "Depreciation allocates long-term asset cost over useful life.",
    "amortization": "Amortization spreads intangible asset cost over time.",
    "stock-based compensation": "SBC pays employees with equity, diluting shareholders but conserving cash.",
    "diluted shares": "Diluted share count includes options and converts that could increase supply.",
    "treasury stock": "Treasury stock is shares repurchased and held by company, reducing float.",
    "authorized shares": "Authorized shares are maximum shares company may issue per charter.",
    "float rotation": "Float rotation measures how many times average volume equals float in a period.",
    "relative volume": "Relative volume compares current volume to average, highlighting unusual activity.",
    "unusual options activity": "Unusual options volume may signal informed or large speculative bets.",
    "block trade": "Block trade is large privately negotiated transaction, often at slight discount or premium.",
    "after-hours earnings gap": "Earnings released after close often gap price at next session open.",
    "pre-market gap trading": "Traders react to overnight news causing pre-market gaps before regular open.",
    "fade the gap": "Fading bets gap will partially fill back toward prior close.",
    "gap and go": "Gap and go strategy trades continuation in direction of opening gap.",
    "opening reversal": "Opening reversal fades initial move after liquidity arrives.",
    "midday chop": "Midday chop is low-volume sideways action between open and close trends.",
    "power hour": "Power hour is last hour of US session with often increased volume and volatility.",
    "monthly options expiration": "Monthly OPEX can increase pinning and gamma effects near large strikes.",
    "year-end tax selling": "Tax-loss selling in December can pressure losers temporarily.",
    "January barometer": "January barometer folklore links year's first month performance to full year.",
    "presidential cycle": "Presidential cycle studies market patterns across four-year election cycles.",
    "FOMC meeting day volatility": "FOMC days often bring elevated volatility around rate decision and press conference.",
    "dot plot": "Fed dot plot shows individual policymakers' rate projections.",
    "forward guidance": "Forward guidance communicates expected future policy path to markets.",
    "hawkish central bank": "Hawkish stance favors fighting inflation with tighter policy.",
    "dovish central bank": "Dovish stance favors supporting growth with easier policy.",
    "yield curve control": "YCC caps yields on certain maturities by central bank buying.",
    "negative interest rates": "Negative rates charge banks for excess reserves, uncommon tool to stimulate lending.",
    "carry trade unwind": "Carry unwind rapidly closes funded trades when volatility spikes or rates shift.",
    "currency intervention band": "Some central banks defend currency within unofficial bands.",
    "CNH vs CNY": "Offshore yuan CNH trades more freely than onshore CNY.",
    "safe haven currency": "JPY, CHF, and sometimes USD strengthen during global risk-off episodes.",
    "commodity currency": "AUD, CAD, and NOK often correlate with resource export prices.",
    "emerging market carry": "EM carry seeks higher local rates but faces devaluation risk.",
    "sovereign default": "Sovereign default is failure to pay government debt obligations.",
    "debt restructuring": "Restructuring renegotiates terms when borrower cannot pay as originally promised.",
    "IMF program": "IMF programs provide crisis lending with policy conditions.",
    "capital controls": "Capital controls restrict cross-border money movement during stress.",
    "currency crisis": "Currency crisis involves sharp devaluation and capital flight.",
    "Asian financial crisis lesson": "1997 crisis showed dangers of fixed rates and short-term foreign debt.",
    "LTCM lesson": "LTCM collapse highlighted leverage and correlation risks in crises.",
    "2008 financial crisis lesson": "2008 showed interconnected credit risk and need for liquidity backstops.",
    "Flash Crash 2010 lesson": "2010 flash crash showed fragility from automated liquidity withdrawal.",
    "GameStop 2021 lesson": "GME saga illustrated short squeeze dynamics and retail coordination.",
    "Archegos lesson": "Archegos failure showed hidden leverage through total return swaps.",
    "SVB 2023 lesson": "SVB highlighted interest rate risk on held-to-maturity bond portfolios.",
    "regulatory circuit lessons": "Past crises drive evolving margin, disclosure, and risk rules.",
}

TEMPLATES = [
    "What is {term}?",
    "Explain {term} in trading.",
    "Define {term}.",
    "How does {term} work in trading?",
    "What is the purpose of {term}?",
    "Why is {term} important for traders?",
    "Can you explain {term} for beginners?",
    "What should I know about {term}?",
    "Tell me about {term} in financial markets.",
    "How do traders use {term}?",
]

PAIR_RE = re.compile(
    r"^User:\s*(?P<question>.+?)\r?\nAssistant:\s*(?P<answer>.+?)(?=\r?\n\r?\nUser:|\Z)",
    re.MULTILINE | re.DOTALL,
)


def generate() -> str:
    lines: list[str] = []
    seen: set[tuple[str, str]] = set()
    for term, answer in KNOWLEDGE.items():
        for template in TEMPLATES:
            question = template.format(term=term)
            key = (question.casefold(), answer.casefold())
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"User: {question}\nAssistant: {answer}\n")
    return "\n".join(lines)


def main() -> None:
    content = generate()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    pairs = len(PAIR_RE.findall(content))
    print(f"Wrote {OUT}")
    print(f"Generated {pairs} Q&A pairs ({len(content):,} characters)")


if __name__ == "__main__":
    main()
